### ISSUE TITLE
Add country name along with the currency. 

### ISSUE THREAD

**Issue by gambhirsharma** [Alkaison/Currency-Converter#1]
There should be a country name along with the currency name. This will be very useful to the users. 

![image](https://github.com/Alkaison/Currency-Converter/assets/69895353/e710b59a-8e8c-40ac-96ce-fff21cfefd55)

**Comment by Alkaison** [comment]
Hi @gambhirsharma, sure it would be great but the current API doesn't provide country names along with current name. If you can help in finding a good API which provides this feature, please contribute to the project as open-source buddy. 😊

**Comment by gambhirsharma** [comment]
Added currency name #2 

[Exchange Rate API](https://app.exchangerate-api.com/) do provide the Country name along with the currency code but that's in their paid plan. 

I used `Intl` constructor to convert the currency code to the currency name.
